<?php
/**
 * Created by PhpStorm.
 * User: weysman
 * Date: 5/12/17
 * Time: 11:25 PM
 */

/** @var Glushko\OpcacheManagement\Block\Adminhtml\Management\Index\Tab\DirectivesTab $block */
?>

<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Directives') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
        <?php foreach ($block->getDirectives() as $directive => $value) : ?>
            <tr>
                <th><strong><?php  echo $directive; ?></strong></th>

                <?php if (is_bool($value)) : ?>
                    <td><?php echo $value ? 'on' : 'off'; ?></td>
                <?php elseif (is_string($value) && '' == $value) : ?>
                    <td><em><?php echo __('no value'); ?></em></td>
                <?php else : ?>
                    <td><?php echo $value; ?></td>
                <?php endif; ?>

            </tr>
        <?php endforeach ; ?>
        </tbody>
    </table>
</div>
