<?php
/**
 * @author Roman Glushko
 * @copyright Copyright (c) 2017 Roman Glushko (http://www.linkedin.com/in/glushko-roman/)
 * @package Glushko_OpcacheManagement
 */
/** @var Glushko\OpcacheManagement\Block\Adminhtml\Management\Index\Tab\MemoryUsageTab $block */
/** @var array $memoryUsage */
$memoryUsage = $block->getMemoryUsage();
?>

<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Memory Usage') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
            <tr>
                <th><strong><?php  echo __('Used Memory') ?></strong></th>
                <td><?php echo $memoryUsage['used_memory']; ?></td>
            </tr>
            <tr>
                <th><strong><?php  echo __('Free Memory') ?></strong></th>
                <td><?php echo $memoryUsage['free_memory']; ?></td>
            </tr>
            <tr>
                <th><strong><?php  echo __('Wasted Memory') ?></strong></th>
                <td><?php echo $memoryUsage['wasted_memory']; ?></td>
            </tr>
            <tr>
                <th><strong><?php  echo __('Current Wasted Percentage') ?></strong></th>
                <td><?php echo $memoryUsage['current_wasted_percentage']; ?></td>
            </tr>
        </tbody>
    </table>
</div>
