<?php
/**
 * @author Roman Glushko
 * @copyright Copyright (c) 2017 Roman Glushko (http://www.linkedin.com/in/glushko-roman/)
 * @package Glushko_OpcacheManagement
 */
/** @var Glushko\OpcacheManagement\Block\Adminhtml\Management\Index\Tab\MemoryUsageTab $block */
?>
<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Memory Usage') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
            <tr>
                <th><strong><?php  echo __('Free Memory') ?></strong></th>
                <td><?php echo $block->getFreeMemory(); ?></td>
            </tr>
            <tr>
                <th><strong><?php  echo __('Used Memory') ?></strong></th>
                <td><?php echo $block->getUsedMemory(); ?></td>
            </tr>
            <tr>
                <th><strong><?php  echo __('Wasted Memory') ?></strong></th>
                <td><?php echo $block->getWastedMemory(); ?></td>
            </tr>
            <tr>
                <th><strong><?php  echo __('Current Wasted Percentage') ?></strong></th>
                <td><?php echo $block->getCurrentWastedPercentage(); ?></td>
            </tr>
        </tbody>
    </table>
</div>
