<?php
/**
 * @author Roman Glushko
 * @copyright Copyright (c) 2017 Roman Glushko (http://www.linkedin.com/in/glushko-roman/)
 * @package Glushko_OpcacheManagement
 */
/** @var Glushko\OpcacheManagement\Block\Adminhtml\Management\Index\Tab\StatisticsTab $block */
/** @var array $statistics */
$statistics = $block->getStatistics();
?>

<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Statistics') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
            <tr>
                <th><strong><?php  echo __('Num Cached Scripts') ?></strong></th>
                <td><?php echo $statistics['num_cached_scripts']; ?></td>
            </tr>
            <tr>
                <th><strong><?php  echo __('Num Cached Keys') ?></strong></th>
                <td><?php echo $statistics['num_cached_keys']; ?></td>
            </tr>
            <tr>
                <th><strong><?php  echo __('Max Cached Keys') ?></strong></th>
                <td><?php echo $statistics['max_cached_keys']; ?></td>
            </tr>
            <tr>
                <th><strong><?php  echo __('Hits') ?></strong></th>
                <td><?php echo $statistics['hits']; ?></td>
            </tr>
            <tr>
                <th><strong><?php  echo __('OOM Restarts') ?></strong></th>
                <td><?php echo $statistics['oom_restarts']; ?></td>
            </tr>
            <tr>
                <th><strong><?php  echo __('Manual Restarts') ?></strong></th>
                <td><?php echo $statistics['manual_restarts']; ?></td>
            </tr>
        </tbody>
    </table>
</div>
